---
title: "Metadata"
output: md_document
---
##Metadata

**Source:** The data used in this dashboard are taken from the PHE fingertips tool: http://fingertips.phe.org.uk/profile-group/mental-health/profile/common-mental-disorders and then aggregated up to NHS region level.

**Indicator:** Newly diagnosed patients with depression who had a review 10-56 days after diagnosis

**Rationale:** The rationale for such follow-up measurement is derived from the recognition that depression is often a chronic disease, yet treatment is often episodic and short-lived.
If treatment with antidepressants is initiated, patients should be followed-up regularly for several months. The NICE clinical guideline 90 recommends that ‘for people started on antidepressants who are not considered to be at increased risk of suicide, normally see them after two weeks. See them regularly thereafter, for example at intervals of two to four weeks in the first three months and then at longer intervals if the response is good. ’Early cessation of treatment is associated with a greater risk of relapse.

The guideline also suggests that a person who has benefited from taking an antidepressant should continue medication for at least six months after remission of an episode of depression. However, one study showed that only up to one-third of patients prescribed antidepressants were still receiving medication at four to six months.

If drug treatment is not started after the initial diagnosis, patients should in any case be reassessed to see whether their symptoms have resolved or worsened to the point where treatment becomes advisable.

**Numerator:** Patients aged 18 or over with a new diagnosis of depression in the preceding 1 April to 31 March, who have been reviewed not earlier than 10 days after and not later than 56 days after the date of diagnosis.

**Denominator:** Patients on disease register (including exclusions) with a new diagnosis of depression and assessment of severity recorded between the preceding 1 April to 31 March

**Caveats:** There are no caveats to be aware of with this dataset